services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: binancetrader-dragonfly
    restart: unless-stopped
    volumes:
      - binancetrader_dragonfly_data:/data
    command: >
      dragonfly
      --dir=/data
      --bind=0.0.0.0
      --port=6379
      --logtostderr
    networks:
      - binancetrader-net
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binancetrader-app
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_URL=redis://dragonfly:6379/0
      - HTTP_LISTEN_ADDRESS=0.0.0.0:8123
    networks:
      - binancetrader-net
    depends_on:
      - dragonfly

networks:
  binancetrader-net:
    name: binancetrader-net
    driver: bridge

volumes:
  binancetrader_dragonfly_data:
    driver: local
